---

- name: "Setup recovery.conf"
  template:
    src: recovery.conf.j2
    dest: "{{ postgresql__data_dir }}/recovery.conf"
    owner: "{{ postgresql__user }}"
    group: "{{ postgresql__user }}"
    mode: 0644
    backup: true
