---

# force a setup on other cluster nodes,
# This is needed later to get cluster nodes informations
- name: Gather facts from other nodes
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{ postgresql_replication__other_nodes }}"
