---

- include_tasks: checks.yml

- include_tasks: gather_cluster.yml

- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: config-user.yml

- include_tasks: config-postgresql.yml

- include_tasks: config-replicas.yml
  when: "postgresql_replication__group_replicas in group_names"
